# Site settings
title: Manohar Amrutkar
email: amrutkarDOTmanoharATgmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blogging about data science..
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://manoharaa.github.io" # the base hostname & protocol for your site
twitter_username: _manoharaa
github_username:  manoharaa

# Build settings
markdown: kramdown
